# File: .github/workflows/tweet.yml

name: Rajasaab Countdown Tweet

on:
  schedule:
    # Runs at 18:30 UTC, which is 12:00 AM IST.
    - cron: '30 18 * * *'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install tweepy

      - name: Run Tweet Script
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: python run_bot.py